#  SPDX-FileCopyrightText: Copyright (c) CloudZero, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

name: CI

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Release Notes
        uses: ./
        with:
          version: "0.0.1"
          releaseNotesDirectory: "tests"
