# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

name: CI

on:
  workflow_dispatch:
    inputs:
      versionIncrementLevel:
        description: Increment level to use for the release
        required: true
        type: choice
        default: patch
        options:
          - maintenance
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main'  && github.ref != 'refs/heads/develop'}}

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version from SemVer
        if: ${{ github.event.inputs.versionIncrementLevel != 'maintenance' }}
        id: version
        uses: flatherskevin/semver-action@v1
        with:
          incrementLevel: ${{ github.event.inputs.versionIncrementLevel }}
          source: tags
      - name: Validate Release Notes
        if: ${{ github.event.inputs.versionIncrementLevel != 'maintenance' }}
        uses: ./
        with:
          version: ${{ steps.version.outputs.nextVersion }}