# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

name: CI

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Release Notes
        uses: ./
        with:
          version: "0.0.1"
          release_notes_file: "tests/0.0.1.md"
