#  SPDX-FileCopyrightText: Copyright (c) CloudZero, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

name: Develop

on:
  workflow_dispatch:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  merge-to-main:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge from develop to master
        uses: ./.github/actions/merge-from-to
        with:
          from-branch: develop
          from-sha: ${{ github.sha }}
          to: main
          app_id: ${{ secrets.PUBLIC_GITHUB_ACTIONS_APP_ID }}
          private_key: ${{ secrets.PUBLIC_GITHUB_ACTIONS_APP_PRIVATE_KEY }}
        