# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

name: Release

on:
  push:
    paths:
      - './action.yml'
    branches:
      - main
    

concurrency:
  group: ${{ github.ref }}-release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Version
        id: version
        uses: flatherskevin/semver-action@v1
        with:
          incrementLevel: patch
          source: tags
      - name: Validate Release Notes
        uses: ./
        id: changelog
        with:
          version: ${{ steps.version.outputs.nextVersion }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.nextVersion }}
          tag_name: ${{ steps.version.outputs.nextVersion }}
          make_latest: true
          target_commitish: ${{ github.sha }}
          body_path: ${{ steps.changelog.outputs.releaseNotesFile }}
      - name: Tag v1
        run: git tag -f v1
      - name: Push v1
        run: git push origin v1 --force