# Copyright (c) 2016-present, CloudZero, Inc. All rights reserved.
# Licensed under the BSD-style license. See LICENSE file in the project root for full license information.

name: Release

on:
  workflow_dispatch:
    inputs:
      versionIncrementLevel:
        description: Increment level to use for the release
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

concurrency:
  group: ${{ github.ref }}-release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - name: Version from SemVer
        id: version
        uses: flatherskevin/semver-action@v1
        with:
          incrementLevel: ${{ github.event.inputs.versionIncrementLevel }}
          source: tags
      - name: Validate Release Notes
        uses: ./
        id: changelog
        with:
          version: ${{ steps.version.outputs.nextVersion }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.nextVersion }}
          tag_name: ${{ steps.version.outputs.nextVersion }}
          make_latest: true
          target_commitish: ${{ github.sha }}
          body_path: ${{ steps.changelog.outputs.releaseNotesFile }}

  failure:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Fail If Branch Is Not Main
        run: |
          echo "This workflow can only be run from the 'main' branch. Current branch: ${{ github.ref }}"
          exit 1
